### ISSUE TITLE
two RFSG cards -> configure_rf() act abnormal behavior

### ISSUE THREAD

**Issue by azviu** [l-johnston/nirfsg#1]
My setup has two PXIe-5654 cards in one chassis. They works normally alone. But when both cards are initiated, the configure_rf() function acts abnormal. If the freq and power written is the same as the existing power, the signal generator output frequency is off. The setup I have use a common 10 MHz ref clock from the chassis (PXI_Clk).

**Comment by l-johnston** [comment]
Thanks for filing the issue. Update to version 0.1.5 fixes the issue.
```python
In [1]: from nirfsg import PXIe_5654
In [2]: sg1 = PXIe_5654("PXI1Slot7")
In [3]: sg2 = PXIe_5654("PXI1Slot10")
In [4]: sg1.configure_rf(1e9, -7)
In [5]: sg2.configure_rf(1.1e9, -10)
In [6]: sg1.initiate()
In [7]: sg2.initiate()
In [8]: sg1.rf_frequency
Out[8]: 1000000000.0
In [9]: sg2.rf_frequency
Out[9]: 1100000000.0
In [10]: nirfsg.__version__
Out[10]: '0.1.5'
```
